name: acer1
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - fsspec=2024.6.1=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py312h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libprotobuf=4.25.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.10=py312h5eee18b_0
  - mkl_random=1.2.7=py312h526ad5a_0
  - mpmath=1.3.0=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.3=py312h06a4308_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - pytorch=2.3.0=cpu_py312h5a90aa3_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - anyio==4.6.0
    - argparse==1.4.0
    - certifi==2024.8.30
    - cloudpickle==3.0.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - fonttools==4.54.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - h11==0.14.0
    - h5py==3.12.1
    - h5sparse==0.1.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - idna==3.10
    - kiwisolver==1.4.7
    - matplotlib==3.9.2
    - packaging==24.1
    - pillow==10.4.0
    - plotly==5.24.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-telegram-bot==21.6
    - scipy==1.14.1
    - six==1.16.0
    - sniffio==1.3.1
    - tenacity==9.0.0
prefix: /home/mainul/.conda/envs/acer1
